# Generated by Django 3.0.8 on 2020-08-03 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_auto_20200803_1452'),
        ('sistema', '0001_initial'),
        ('productos', '0002_auto_20200731_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_remision', models.CharField(max_length=30)),
                ('fecha_de_emision', models.DateField(default=datetime.date.today)),
                ('motivo_del_traslado', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_de_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_de_comprobante_de_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_de_timbrado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_expedicion', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('fecha_de_inicio_del_traslado', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('fecha_estimada_de_termino_del_traslado', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('direccion_del_punto_de_partida', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento_de_partida', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_del_punto_de_llegada', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento_de_llegada', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometros_estimados_de_recorrido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cambio_de_fecha_de_termino_del_traslado_o_punto_de_llegada', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmado'), ('ANU', 'Anulado')], default='PEN', editable=False, max_length=3)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Funcionario')),
                ('ciudad_de_llegada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_de_llegada', to='sistema.Ciudad')),
                ('ciudad_de_partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_de_partida', to='sistema.Ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Vehiculo')),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
            },
        ),
        migrations.CreateModel(
            name='DetalleDeRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remisiones.Remision')),
                ('unidad_de_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.UnidadDeMedida')),
            ],
            options={
                'verbose_name': 'Detalle de la remisión',
                'verbose_name_plural': 'Detalles de la remisión',
            },
        ),
    ]
