# Generated by Django 3.0.8 on 2020-08-14 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('clientes', '0001_initial'),
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remision',
            options={'verbose_name': 'Nota de remisión', 'verbose_name_plural': 'Notas de remisión'},
        ),
        migrations.AlterField(
            model_name='remision',
            name='punto_de_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.PuntoEntregaCliente'),
        ),
        migrations.AlterField(
            model_name='remision',
            name='punto_de_partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Local'),
        ),
    ]
