# Generated by Django 3.0.8 on 2020-08-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200731_1631'),
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallederemision',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto', verbose_name='Descripción detallada'),
        ),
    ]
