# Generated by Django 3.0.8 on 2020-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0002_auto_20200803_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='fecha_de_facturacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
