# Generated by Django 3.0.8 on 2020-08-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200820_1648'),
        ('remisiones', '0002_auto_20200814_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='ciudad_de_llegada',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='departamento_de_llegada',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='direccion_del_punto_de_llegada',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='punto_de_entrega',
        ),
        migrations.AddField(
            model_name='remision',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.PuntoEntregaCliente'),
            preserve_default=False,
        ),
    ]
