# Generated by Django 3.0.8 on 2020-08-03 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_auto_20200803_1452'),
        ('productos', '0002_auto_20200731_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_factura', models.CharField(max_length=30)),
                ('fecha_de_emision', models.DateField(default=datetime.date.today)),
                ('condicion_de_venta', models.CharField(choices=[('CON', 'Contado'), ('CRE', 'Crédito')], default='CON', max_length=3)),
                ('iva', models.CharField(choices=[('10', '10 %'), ('05', '5 %'), ('00', 'exenta')], default='10', max_length=2)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmado'), ('ANU', 'Anulado')], default='PEN', editable=False, max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Factura de venta',
                'verbose_name_plural': 'Facturas de venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.Venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
            },
        ),
    ]
