# Generated by Django 3.0.8 on 2020-08-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalledeventa',
            options={'verbose_name': 'Detalle de venta', 'verbose_name_plural': 'Detalles de venta'},
        ),
        migrations.RenameField(
            model_name='detalledeventa',
            old_name='factura',
            new_name='venta',
        ),
    ]
