# Generated by Django 3.0.8 on 2020-08-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_puntoentregacliente_departamento'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='punto_de_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.PuntoEntregaCliente', verbose_name='Dirección del punto de entrega'),
        ),
    ]
