# Generated by Django 3.0.8 on 2020-09-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200908_1425'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='punto_de_entrega',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.PuntoEntregaCliente', verbose_name='Dirección del punto de entrega'),
        ),
    ]
