# Generated by Django 3.0.8 on 2020-08-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_punto_de_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
