# Generated by Django 3.0.8 on 2020-10-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('ventas', '0002_auto_20200908_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Vehiculo'),
        ),
    ]
