# Generated by Django 3.0.8 on 2020-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200803_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='condicion_de_venta',
            field=models.CharField(choices=[('CON', 'Contado'), ('CRE', 'Crédito')], default='CON', max_length=3, verbose_name='Condición de venta'),
        ),
    ]
