# Generated by Django 3.0.8 on 2020-08-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0003_remision_fecha_de_facturacion'),
        ('ventas', '0003_auto_20200803_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemisionEnVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remisiones.Remision')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.Venta')),
            ],
        ),
    ]
