# Generated by Django 3.0.8 on 2020-08-07 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remisionenventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisionenventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
    ]
