# Generated by Django 3.0.8 on 2020-08-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='departamento',
        ),
    ]
