# Generated by Django 3.0.8 on 2020-07-31 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocliente',
            options={'verbose_name': 'Producto por cliente', 'verbose_name_plural': 'Productos por cliente'},
        ),
        migrations.AlterField(
            model_name='productocliente',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
