# Generated by Django 3.0.8 on 2020-08-12 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200731_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocliente',
            name='fecha_de_creacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Inicio de vigencia'),
        ),
    ]
