# Generated by Django 3.0.8 on 2020-08-21 00:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razón social')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección de facturación')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('dia_de_presentacion', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='día de presentación de facturas')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoEntregaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200, verbose_name='dirección')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Punto de entrega',
                'verbose_name_plural': 'Puntos de entrega',
            },
        ),
    ]
